# ASSIGNMENT - 5

# SENTIMENT ANALYSIS

In [3]:
# Importing library

import pandas as pd

In [7]:
# Importing Dataset

df = pd.read_json( r"C:\Users\Yogesh Bhardwaj\Downloads\Arts_Crafts_and_Sewing_5.json",lines=True)
df.sample(10)

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
552,5,True,"09 27, 2016",A36KHGA778VNPI,B0000302YN,{'Style:': ' Engraver with Letter/Number Templ...,ww,Looks like a good set,Got it,1474934400,NaN,NaN
357024,5,True,"04 14, 2016",A7FN3H2P311NO,B00P14S65G,NaN,Chasetwins,Love it!,Five Stars,1460592000,5,[https://images-na.ssl-images-amazon.com/image...
23432,5,True,"10 29, 2013",A2KB8LQPT7AH4O,B000HF6YX0,{'Style Name:': ' 6 Starter Set'},Katrina,great set to start with im using it for my fir...,great set to start with,1383004800,NaN,NaN
369315,4,True,"02 8, 2016",A11NMMQEI6HFBA,B00US4UOWC,{'Size:': ' 4 oz'},Kim in MD,I purchased this product to make older book pa...,Works pretty well for my purposes,1454889600,19,NaN
424562,5,True,"10 13, 2017",A2L2I9WKKJQIWR,B0010EO14Q,NaN,Ann M.,This is so nice to have next to my sewing mach...,Must Have Tool for Quilters,1507852800,2,NaN
444527,2,True,"10 2, 2015",A1GS1EX68K53ZS,B0055739HO,NaN,tonjia cooper,This product broke after three uses.,ok for the price,1443744000,NaN,NaN
34069,5,True,"06 21, 2015",A1TWCHR2IK9W4X,B000QV050S,NaN,Monzilla,They are so cute,How cute,1434844800,NaN,NaN
329802,5,True,"05 24, 2018",A3266V4RPDWRA9,B00IYUBWWS,"{'Size:': ' 10mm', 'Color:': ' 23) Hematite Ro...",Mastiff Mom,Beautiful beads; great price; fast delivery; 1...,Beautiful beads; great price; fast delivery; 1...,1527120000,NaN,NaN
267037,5,False,"02 28, 2016",A2SIB10FYDUW0K,B00916Y4YM,NaN,Jessica,This is my second mechanical sewing machine an...,great mechanical machine,1456617600,8,NaN
451335,5,True,"04 7, 2017",AAXJHKJWI8CXJ,B007GYFAU8,NaN,Florida Mom,Nice sayings to put inside homemade greeting c...,Nice sayings,1491523200,NaN,NaN

# Get the Bing Liu lexicon

In [5]:
# Get the Bing Liu lexicon

from sklearn import preprocessing
import nltk
nltk.download('opinion_lexicon')
from nltk.corpus import opinion_lexicon
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package opinion_lexicon to C:\Users\Yogesh
[nltk_data]     Bhardwaj\AppData\Roaming\nltk_data...
[nltk_data]   Package opinion_lexicon is already up-to-date!

In [3]:
print('Total number of words in opinion lexicon', len(opinion_lexicon.words()))
print('Examples of positive words in opinion lexicon',
opinion_lexicon.positive()[:10])
print('Examples of negative words in opinion lexicon',
opinion_lexicon.negative()[:10])

Total number of words in opinion lexicon 6789
Examples of positive words in opinion lexicon ['a+', 'abound', 'abounds', 'abundance', 'abundant', 'accessable', 'accessible', 'acclaim', 'acclaimed', 'acclamation']
Examples of negative words in opinion lexicon ['2-faced', '2-faces', 'abnormal', 'abolish', 'abominable', 'abominably', 'abominate', 'abomination', 'abort', 'aborted']

In [4]:
# Let's create a dictionary which we can use for scoring our review text

nltk.download('punkt')
df.rename(columns={"reviewText": "text"}, inplace=True)
pos_score = 1
neg_score = -1
word_dict = {}

[nltk_data] Downloading package punkt to C:\Users\Yogesh
[nltk_data]     Bhardwaj\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [5]:
# Adding the positive words to the dictionary

for word in opinion_lexicon.positive():
    word_dict[word] = pos_score

In [6]:
# Adding the negative words to the dictionary

for word in opinion_lexicon.negative():
    word_dict[word] = neg_score

In [7]:
# Function to do the math

def bing_liu_score(text):
    sentiment_score = 0
    bag_of_words = word_tokenize(text.lower())
    for word in bag_of_words:
        if word in word_dict:
            sentiment_score += word_dict[word]
    return sentiment_score

In [8]:
# Make sure all texts are non-empty and are type text then call the function

df['text'].fillna('no review', inplace=True)
df['Bing_Liu_Score'] = df['text'].apply(bing_liu_score)

In [9]:
# Let’s see the output

df[['overall',"text", 'Bing_Liu_Score']].head(10)

   overall                                               text  Bing_Liu_Score
0        4                Contains some interesting stitches.               1
1        5  I'm a fairly experienced knitter of the one-co...              22
2        4  Great book but the index is terrible. Had to w...               0
3        5  I purchased the Kindle edition which is incred...               4
4        5  Very well laid out and very easy to read.\n\nT...               5
5        5  Beginning her career as a freelance knitter, M...              15
6        5  This is a terrific stitch handbook (and I have...               9
7        4  The book needs to be coil bound. The content i...               1
8        5  I really am enjoying this book! I like the siz...              12
9        5  Just received this book and looked over it cov...               6

In [10]:
#  Does the sentiment count match the “rating” given by the customers?

df.groupby('overall').agg({'Bing_Liu_Score':'mean'})

         Bing_Liu_Score
overall
1             -0.255049
2              0.566098
3              1.158796
4              2.028146
5              2.130005